export { PROTOCOL_VERSION, type ProtocolVersion } from './version.ts'
export { HOST_MACHINE_KINDS, hostMachineKindFromHints, hostMachineLabel, isHostIdentity, isHostMachineKind, normalizeHostIdentity, shortHostName, type HostArch, type HostIdentity, type HostMachineKind, type HostOs } from './host-identity.ts'
export { describePiAdapter, isHarnessAdapter, type HarnessAdapter, type HarnessCapabilities } from './adapter.ts'
export {
  applyWorkbenchCommand,
  isSleepPreventionCommand,
  isWorkbenchCommand,
  SLEEP_PREVENTION_COMMAND_TYPES,
  WORKBENCH_COMMAND_TYPES,
  type SleepPreventionCommand,
  type WorkbenchCommand,
  type WorkbenchCommandType,
} from './commands.ts'
export {
  applyLiveOps,
  applySnapshotPatch,
  diffSnapshots,
  isLiveOnlyPatch,
  isPatchEmpty,
  liveTargetResync,
  serializeSnapshot,
  snapshotNeedsLiveResync,
  LIVE_QUEUE_BUDGET_BYTES,
  SNAPSHOT_IMAGE_LIMIT_BYTES,
  type DiffSnapshotOptions,
  type LiveContentOp,
  type OmittedImageData,
  type SnapshotComposerImage,
  type SnapshotKey,
  type SnapshotPatch,
  type WorkbenchSnapshot,
} from './snapshot.ts'
export {
  canonicalTranscriptEntryId,
  clampTranscriptDetailLimit,
  estimateJsonBytes,
  estimateMessageBytes,
  findOmittedTranscriptEntry,
  findTranscriptDetail,
  isOmittedTranscriptMessage,
  isTranscriptDetailRef,
  liveBlockEntryId,
  mergeTranscriptDetail,
  messageMatchesTranscriptEntry,
  overlayExpandedTranscript,
  pageTranscriptDetail,
  projectLiveAssistant,
  projectLiveTools,
  projectTranscriptMessages,
  projectWorkbenchSnapshot,
  sameSessionFile,
  TranscriptExpansionCache,
  TRANSCRIPT_BODY_BUDGET_BYTES,
  TRANSCRIPT_DETAIL_AUTO_MAX_BYTES,
  TRANSCRIPT_DETAIL_MAX_PAGES,
  TRANSCRIPT_DETAIL_PAGE_BYTES,
  TRANSCRIPT_DETAIL_PREFETCH_CONCURRENCY,
  TRANSCRIPT_PREVIEW_CHARS,
  TRANSCRIPT_RESERVED_TAIL_BYTES,
  TRANSCRIPT_WIRE_BUDGET_BYTES,
  type TranscriptDetail,
  type TranscriptDetailRef,
  type TranscriptDetailSource,
  type TranscriptProjectOptions,
} from './transcript.ts'
export { parseClientMessage, parseServerMessage, type AttentionEvent, type ClientMessage, type ServerMessage } from './messages.ts'
export {
  encodeFrames,
  FrameAssembler,
  isWireFrame,
  MAX_ASSEMBLED_BYTES,
  MAX_WS_FRAME_BYTES,
  splitUtf8,
  utf8ByteLength,
  type WireFrame,
} from './frames.ts'
export {
  applyTerminalCommand,
  clampTerminalCols,
  clampTerminalRows,
  DEFAULT_TERMINAL_COLS,
  DEFAULT_TERMINAL_ROWS,
  isTerminalCommand,
  MAX_TERMINAL_WRITE_CHARS,
  TERMINAL_COMMAND_TYPES,
  type RemoteTerminalFrame,
  type RemoteTerminalSession,
  type RemoteTerminalSnapshot,
  type TerminalCommand,
  type TerminalCommandTarget,
} from './terminal.ts'
